name: PayFace
description: Ini Deskripsi

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  datetime_picker_formfield: "^0.4.2"
  cupertino_icons: ^0.1.2
  passwordfield: ^0.0.4
  intl: ^0.15.8
  flutter_widgets: ^0.1.6
  dropdownfield: ^1.0.0
  #permission: ^0.1.3
  #simple_permissions: ^0.1.9
  permission_handler: ^3.2.2
  http: ^0.12.0+2
  build_runner: ^1.3.3
  json_serializable: ^2.2.1
  json_annotation: ^2.2.0
  camera: ^0.5.4+2
  path_provider: ^1.3.0
  path: ^1.6.4
  fluttertoast: ^3.1.3
  pie_chart: ^1.2.0
  parse_server_sdk: ^1.0.24
  equatable: ^0.6.0
  shared_preferences: ^0.5.3+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/logo.png # <-Logo Diganti
    - asset/images/welcome.png # <- Gambar Welcome
    - asset/images/topup.png
    - asset/images/transaksi.png
    - asset/images/user.png
    - asset/images/rupiah.png
    - asset/images/registration.png
    - asset/contohData.txt
    - asset/images/logo_1.jpeg
    - asset/images/wallet.png
  fonts:
    - family: Nunito
      fonts: 
        - asset: asset/font/Nunito.ttf

